server:
  port: 8080

spring:
  application:
    name: ai-costumer-service
  ai:
    # AI-API基础配置
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${API_KEY_BAILIAN}
      chat:
        options:
          model: glm-5.3
          max-tokens: 1024
      # 向量模型和维度配置
      embedding:
        options:
          model: qwen3.7-text-embedding
          dimensions: 1024
    # 向量数据库配置
    vectorstore:
      milvus:
        client:
          host: "127.0.0.1"
          port: 19530
          username: ""
          password: ""
        database-name: "default"
        collection-name: "ai_costumer_service"
        embedding-dimension: 1024
        index-type: IVF_FLAT
        metric-type: cosine
        initialize-schema: true
  # MySQL 配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai_customer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zh0604
  # 设置文件上传最大上限
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


############## Sa-Token 配置 (文档: https://sa-token.com) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认7天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

aliyun:
  oss:
    # butcet location area
    endpoint: oss-cn-wuhan-lr.aliyuncs.com
    # AK amount to the username
    access-key-id: LTAI5t8RRmx1cDuQCzo3gRAn
    # SK amount to the password
    access-key-secret: ${ALIBABA_OSS_ACCESS_KEY_SECRET_AI_CUSTOMER_SERVICE}
    # bucket name
    bucket-name: ai-costumer-service
    # bucket Access the domain name
    bucket-url: ai-costumer-service.oss-cn-wuhan-lr.aliyuncs.com